### ISSUE TITLE
Spacing between custom button cards

### ISSUE THREAD

**Issue by flyingdutchman7588** [qiz-li/lovelace-soft-ui#44]
I am using the soft ui with a custom button card integrated in a grid card. However, there is too much spacing in between the buttons and I would like shorten the distance between the buttons. How do I do that? 

![image](https://user-images.githubusercontent.com/37387465/125673750-fbf0f497-3e74-4e54-a22f-98c89ee8713c.png)

**Comment by qiz-li** [comment]
Hi @flyingdutchman7588, you would need to adjust the `margin` option inside the style.
